export const pricingInfo = [
    {
        id: 1,
        title: "Free",
        amount: 0,
        text1: "Aida dere",
        text2: "Nec feugiat nisl",
        text3: "Nulla at volupat dola",
        text4: "Pharetra massa",
        text5: "Massa ultricies mi",
    },
    {
        id: 2,
        title: "Business",
        amount: 19,
        text1: "Aida dere",
        text2: "Nec feugiat nisl",
        text3: "Nulla at volupat dola",
        text4: "Pharetra massa",
        text5: "Massa ultricies mi",
    },
    {
        id: 3,
        title: "Developer",
        amount: 29,
        text1: "Aida dere",
        text2: "Nec feugiat nisl",
        text3: "Nulla at volupat dola",
        text4: "Pharetra massa",
        text5: "Massa ultricies mi",
    },
    {
        id: 4,
        title: "Ultimate",
        amount: 49,
        text1: "Aida dere",
        text2: "Nec feugiat nisl",
        text3: "Nulla at volupat dola",
        text4: "Pharetra massa",
        text5: "Massa ultricies mi",
    },
]